name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: [2.7, 3.0, 3.1, 3.2, 3.3, head]
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle install
      run: bundle install
    - name: Setup project
      run: bundle exec rake appraisal:install
    - name: Run tests for Rails 6.0
      if: ${{ matrix.ruby <= 3.3 }}
      run: bundle exec appraisal rails-6-0 rake test
    - name: Run tests for Rails 6.1
      if: ${{ matrix.ruby <= 3.3 }}
      run: bundle exec appraisal rails-6-1 rake test
    - name: Run tests for Rails 7.0
      if: ${{ matrix.ruby <= 3.3 }}
      run: bundle exec appraisal rails-7-0 rake test
    - name: Run tests for Rails 7.1
      run: bundle exec appraisal rails-7-1 rake test
    - name: Run tests for Rails edge
      run: bundle exec appraisal rails-edge rake test
      if: ${{ matrix.ruby >= 3.1 || matrix.ruby == 'head' }}
    - uses: paambaati/codeclimate-action@v5
      if: ${{ matrix.ruby == 3.2 && !github.base_ref }}

  standard:
    name: Run standard
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Setup project
        run: bundle install
      - name: Rake standard
        run: bundle exec rake standard
